---
# https://linuxconfig.org/how-to-install-docker-in-rhel-8
# You should be using podman and buildah instead!

- name: Uninstall old versions
  dnf:
    name: >-
        docker, docker-client, docker-client-latest,
        docker-common, docker-engine, docker-latest,
        docker-latest, docker-latest-logrotate, docker-logrotate,
    state: absent

- name: Setup yum repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    checksum: "sha256:6650718e0fe5202ae7618521f695d43a8bc051c539d7570f0edbfa5b4916f218"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'

- name: Install Docker-CE
  dnf:
    name: docker-ce-3:18.09.1, docker-ce-cli, containerd.io
    state: present
