---
# tasks file for docker_ce

- name: End the play for hosts that run RHEL 8
  meta: end_host
  when:
  - ansible_distribution == 'RedHat'
  - ansible_distribution_version|int >= 8
  - not force_docker_ce_on_rhel_8

- include: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version']|int <= 7

- include: install_RedHat.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int <= 8

- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int == 30

- include: configure.yml
