---
# Install KVM on CentOS

# - debug:
#    var: kvm_required_packages_centos

- name: install KVM packages on CentOS
  yum:
    name: "{{ kvm_required_packages_centos_7 }}"
    state: present
  when: ansible_facts['distribution'] == "CentOS"
  become: yes
