---
# vars file for virtualbox

vboxdrv_required_packages_centos_7:
  - binutils
  - qt
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel
  - dkms

vboxdrv_required_packages_rhel_8:
  - binutils
  - qt
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel
  - dkms

vboxdrv_required_packages_fedora_30:
  - binutils
  - qt
  - gcc
  - make
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel
  - kernel-headers
  - kernel-devel
  - dkms
