---
# tasks file for packer

- name: download packer zip
  get_url:
    url: "{{ packer_zip_url }}"
    checksum: sha256: {{ packer_checksum_url }}
    dest: /tmp/packer.zip

- name: unpack packer
  unarchive:
    src: "{{ packer_zip }}"
    dest: /usr/local/bin
    copy: no

- name: remove packer zip
  file:
    path: /tmp/packer.zip
    state: absent
