galaxy_info:
  author: Mihai Criveti
  description: Cloud Native Competency Leader
  company: Mihai Criveti
  license: MIT
  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  platforms:
    - name: Fedora
      versions:
        - all
        - 30
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - 18.04
    - name: Debian
      versions:
        - 10

  galaxy_tags:
    - vmware
    - virtualization
    - debian
    - ubuntu
    - rhel
    - centos
    - fedora

# dependencies: []
