---
# vars file for vmtools

# SSH service name
_sshd_service_name:
  default: sshd
  Debian: ssh
  Ubuntu: ssh

sshd_service_name: "{{ _sshd_service_name[ansible_distribution] | default(_sshd_service_name['default']) }}"

# VMware Tools packages to install
_packages_vmware_tools:
  all:
    - "open-vm-tools"
  CentOS:
    - "open-vm-tools"

# KVM tools packages to install
_packages_kvm_tools:
  all:
    - "qemu-guest-agent"
  CentOS:
    - "qemu-guest-agent"

# VirtualBox tools prereq packages to install
_packages_virtualbox_tools:
  all:
    - "dkms"
  CentOS:
    - "gcc"

packages_vmware_tools: "{{ _packages_vmware_tools['all'] + ( _packages_vmware_tools[ansible_distribution] | default([]) ) }}"
packages_kvm_tools: "{{ _packages_kvm_tools['all'] + ( _packages_kvm_tools[ansible_distribution] | default([]) ) }}"
packages_virtualbox_tools: "{{ _packages_virtualbox_tools['all'] + ( _packages_virtualbox_tools[ansible_distribution] | default([]) ) }}"
