---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: docker
lint:
  name: yamllint
platforms:
  - name: debian-10
    image: debian:10
    pre_build_image: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: docker-debian-10
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
