---
# Install VirtualBox on Fedora

- name: setup VirtualBox yum repository on Fedora 30
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/29/$basearch
    enabled: 1
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version']|int >= 30

- name: install VirtualBox
  yum:
    name: "VirtualBox-{{ virtualbox_version }}.{{ ansible_architecture }}"
    state: present

- name: install VirtualBox vboxdrv requirements on Fedora
  yum:
    name: "{{ vboxdrv_required_packages_fedora_30 }}"
    state: present
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version']|int >= 30

- name: register current kernel
  command: "uname -r"
  register: current_kernel
  tags:
    - skip_ansible_lint

- name: install current kernel devel
  yum:
    name: "kernel-devel-{{ current_kernel.stdout }}"
    state: present
