---
# Install VirtualBox on Ubuntu

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: yes
    name: "{{ ubuntu_prereq_packages }}"
    state: present

- name: add Virtualbox apt signing key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
    - https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc

- name: setup VirtualBox apt repository on Ubuntu
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian bionic contrib"
    state: present

- name: install VirtualBox
  apt:
    update_cache: yes
    name: "virtualbox-{{ virtualbox_version }}"
    state: present

- name: install VirtualBox vboxdrv requirements on Ubuntu
  apt:
    name: "{{ vboxdrv_required_packages_ubuntu_1804 }}"
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"
