---
# tasks file for vmware_workstation

- include: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS"

- include: install_RedHat.yml
  when: ansible_facts['distribution'] == "RedHat"

- include: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora"

- include: install_Ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu"

- include: install_Debian.yml
  when: ansible_facts['distribution'] == "Debian"

- include: install_VMware.yml

- include: patch_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version']|int == 30

- include: configure.yml
